"================================================================ {
"                 Base config 基本设置
"================================================================
"
" coding and char
language messages zh_CN.UTF-8            " 设置语言
set ambiwidth=double                     " 解决中文标点显示的问题
set encoding=utf-8                       " 编码设置
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1,gbk,gb2312 " 设置文件编码
set helplang=cn                          " 设置帮助文档语言
set langmenu=zh_CN.UTF-8                 " 设置语言
set linebreak                            " 设置换行符为unix格式
set nolist                                 " 显示特殊字符
set nrformats=octal,hex                  " 设置数字格式
set sidescroll=10                        " 移动到看不见的字符时，自动向右滚动是10个字符
set conceallevel=0                       " 不隐藏特殊字符

" indent
set autoindent                           " 自动对齐
set shiftwidth=4                         " 设定自动缩进为4个字符
set smartindent                          " 智能缩进

" tab
set expandtab                            " 使用空格代替tab
set smarttab                             " 智能tab
set softtabstop=4                        " tab缩进
set tabstop=4                            " tab缩进
%retab!                                  " 将tab转换为空格
set tabpagemax=10                        " 设置标签页最大数量
set showtabline=2                        " 始终显示标签栏

" fold
set foldenable                           " 启动 vim 时打开折叠代码
set foldlevelstart=99                    " 设置折叠级别的初始值
set foldmethod=expr                      " 设置折叠方法为表达式
set nofoldenable                         " 启动 vim 时关闭折叠代码
set foldexpr=nvim_treesitter#foldexpr()

" win
set splitright                           " 设置左右分割窗口时，新窗口出现在右侧
set splitbelow                           " 设置水平分割窗口时，新窗口出现在底部

" file type
filetype on                              " 开启文件类型检测
filetype plugin indent on                " 开启文件类型插件和缩进检测
filetype plugin on                       " 开启文件类型插件

" file
set hidden                               " 是否显示隐藏文件
set nobackup                             " 不需要备份
set nowritebackup                        " 是否备份
set updatetime=300                       " 设置更新时间
set noswapfile                           " 禁止生成临时文件

" file 
set autoread                             " 文件自动检测外部更改
set autowriteall                         " 当文件被修改时，自动保存
set confirm                              " 当文件变化时，是否弹出确认框

" cmd
set cmdheight=2                          " 命令行高度
set history=10000                        " 历史记录数
set shortmess+=c                         " shortmess 不缩短命令信息
set showcmd                              " 显示输入的命令
set ttimeoutlen=0                        " 设置键盘映射等待时间

" highlight and colorscheme
set hlsearch                             " 高亮查找匹配
set showmatch                            " 显示匹配
set sm!                                  " 高亮显示匹配括号
set showmatch                            " 高亮显示匹配的括号
set colorcolumn=80                       " 设置颜色列
set background=dark                       " 背景颜色
colorscheme desert                       " 配色方案

" editor
set backspace=indent,eol,start           " 设置退格键的行为
"set cursorline                          " 高亮显示当前行
"set cursorcolumn                        " 高亮显示当前列
set modelines=0                          " 禁用模式行
set mousehide                            " 输入时隐藏光标
set mouse=a                              " 使用鼠标
set paste                                " 粘贴模式
set nowrap                               " 不自动折行
set selection=exclusive                  " 选择模式，inclusive是包含行尾，exclusive是不包含行尾
set number                               " 显示行号
set relativenumber                       " 显示相对行号
set ruler                                " 显示标尺，在右下角显示光标位置
set iskeyword=_,$,@,%,#,-                " 设置关键字，用于搜索和替换
set clipboard=unnamedplus                " 共享系统剪贴板
set guioptions-=l                        " 禁止显示滚动条
set guioptions-=L                        " 禁止显示滚动条
set guioptions-=r                        " 禁止显示滚动条
set guioptions-=R                        " 禁止显示滚动条
set guioptions-=m                        " 禁止显示菜单和工具条
set guioptions-=T                        " 禁止显示菜单和工具条
set scrolloff=4                          " 光标移动到buffer顶部和底部时保持的距离
set ignorecase                           " 忽略大小写
set smartcase                            " 智能大小写
set wildmenu                             " 
set wildmode=longest:full,full           " 
set nocompatible                         " 去除vi一致性
set novisualbell                         " 不要闪烁
set redrawtime=1000                      " 设置重绘时间，单位毫秒
set ttyfast                              " 加快终端响应速度
set completeopt=menuone,noinsert         " 设置自动补全
set complete=.

set vb t_vb=                             " 关闭可视响铃
set synmaxcol=200                        " 语法高亮最大列数
let &t_SI = "\<Esc>]50;CursorShape=1\x7" " 设置光标为竖线
let &t_SR = "\<Esc>]50;CursorShape=2\x7" " 设置光标为块
let &t_EI = "\<Esc>]50;CursorShape=0\x7" " 设置光标为下划线
set completeopt=longest,menu             " 自动补全配置让Vim补全菜单行为跟IDE一致
set backspace=indent,eol,start           " 允许用退格键删除字符

syntax on                                " 语法高亮
syntax sync minlines=256                 " 语法高亮

set tags=./tags,tags,./.tags,./ctags,ctags,./.ctags
set path+=**                             " 设置搜索路径
let g:markdown_fenced_languages =['golang', 'go', 'rust', 'c', 'cpp', 'python', 'javascript']

"================================================================
"
"
augroup relative_numbser
    autocmd!
    autocmd InsertEnter * :set norelativenumber
    autocmd InsertLeave * :set relativenumber
augroup END

autocmd FileType gitcommit set colorcolumn=80

"================================================================
"
nnoremap <SPACE> <Nop>
let mapleader = " "

nnoremap <silent>  j gj
nnoremap <silent>  k gk

command! Reload :source ~/workbench/nvim/vimrc<CR>
"
"================================================================

" 设置状态行显示常用信息
" %F 完整文件路径名
" %m 当前缓冲被修改标记
" %m 当前缓冲只读标记
" %h 帮助缓冲标记
" %w 预览缓冲标记
" %Y 文件类型
" %b ASCII值
" %B 十六进制值
" %l 行数
" %v 列数
" %p 当前行数占总行数的的百分比
" %L 总行数
" %{...} 评估表达式的值，并用值代替
" %{"[fenc=".(&fenc==""?&enc:&fenc).((exists("+bomb") && &bomb)?"+":"")."]"} 显示文件编码
" %{&ff} 显示文件类型
set laststatus=2                         " 始终显示状态栏
set statusline=%1*%F%m%r%h%w%=\ 
set statusline+=%2*\ %Y\ \|\  
set statusline+=%3*%{\"\".(\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\"+\":\"\").\"\"}\ 
set statusline+=%4*[%l:%v]\ 
set statusline+=%5*%p%%\ \|\ 
set statusline+=%6*%LL\ 

hi User1 cterm=none ctermfg=gray ctermbg=darkgray
hi User2 cterm=none ctermfg=darkgrey ctermbg=gray
hi User3 cterm=bold ctermfg=darkgrey ctermbg=gray
hi User4 cterm=bold ctermfg=yellow ctermbg=gray
hi User5 cterm=none ctermfg=darkgrey ctermbg=gray
hi User6 cterm=none ctermfg=darkgrey ctermbg=gray

" 设置tab栏
" 选中的tab颜色
hi SelectTabLine term=Bold cterm=Bold ctermfg=DarkYellow ctermbg=LightGray
hi SelectPageNum cterm=None ctermfg=DarkRed ctermbg=LightGray
hi SelectWindowsNum cterm=None ctermfg=DarkCyan ctermbg=LightGray
" 未选中状态的tab
hi NormalTabLine cterm=None ctermfg=Gray ctermbg=DarkGray
hi NormalPageNum cterm=None ctermfg=Gray ctermbg=DarkGray
hi NormalWindowsNum cterm=None ctermfg=Gray ctermbg=DarkGray
" tab栏背景色
hi TabLineFill term=reverse ctermfg=5 ctermbg=7 guibg=#6c6c6c

" 设置netrw-------------------------------------
let g:netrw_banner = 0         " 设置是否显示横幅
let g:netrw_liststyle = 3      " 设置目录列表样式：树形
let g:netrw_browse_split = 4   " 在之前的窗口编辑文件
let g:netrw_altv = 1           " 水平分割时，文件浏览器始终显示在左边
let g:netrw_winsize = 20       " 设置文件浏览器窗口宽度为25%
let g:netrw_list_hide= '^\..*' " 不显示隐藏文件 用 a 键就可以显示所有文件、 隐藏匹配文件或只显示匹配文件
" 自动打开文件浏览器
" augroup ProjectDrawer
"     autocmd!
"     autocmd VimEnter * :Vexplore
" augroup END

"
"================================================================ }
